"""primary&foreign key

Revision ID: 762ab2b90ee6
Revises: 78e39552106d
Create Date: 2025-05-08 21:15:53.088495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '762ab2b90ee6'
down_revision: Union[str, None] = '78e39552106d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'karma_score', 'users', ['user_id'], ['user_id'])
    op.drop_constraint('pending_reflection_user_id_fkey', 'pending_reflection', type_='foreignkey')
    op.create_foreign_key(None, 'pending_reflection', 'users', ['user_id'], ['user_id'])
    op.drop_constraint('reflection_response_user_id_fkey', 'reflection_response', type_='foreignkey')
    op.create_foreign_key(None, 'reflection_response', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'reflection_response', type_='foreignkey')
    op.create_foreign_key('reflection_response_user_id_fkey', 'reflection_response', 'karma_score', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'pending_reflection', type_='foreignkey')
    op.create_foreign_key('pending_reflection_user_id_fkey', 'pending_reflection', 'karma_score', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'karma_score', type_='foreignkey')
    # ### end Alembic commands ###
