"""creating boost_no field

Revision ID: 845c795533d1
Revises: 980b58e27b91
Create Date: 2025-05-05 09:23:13.349606

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845c795533d1'
down_revision: Union[str, None] = '980b58e27b91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('karma_score', sa.Column('boost_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('karma_score', 'boost_count')
    # ### end Alembic commands ###
