"""reflection_response table

Revision ID: 9f09b9fc4052
Revises: 123bbd79b453
Create Date: 2025-05-05 11:43:00.765727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f09b9fc4052'
down_revision: Union[str, None] = '123bbd79b453'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reflection_response',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('reflection_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('action', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reflection_id'], ['pending_reflection.reflection_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['karma_score.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reflection_response')
    # ### end Alembic commands ###
